### ISSUE TITLE
while 루프에 대해서 분석기 무한루프

### ISSUE THREAD

**Issue by gugusny5758** [plasse/program_analysis#4]
소스코드에 무한 루프가 있으면 분석기 프로그램이 종료되지 않습니다.
test006.txt와 같이 무한 루프를 도는 while루프가 존재하면 데이터 플로우는 정상적으로 출력되는데 분석기 프로그램의 종료가 되지 않습니다.
mutation은 주석처리되어있는상태에서의 실행 결과 script입니다.

$ ./main.byte test/ml/test006.txt
AST :
[x:@2 := source()]@1;
[y:@4 := 1]@3;
while y:5 < 3 do @9
[y:@8 := y:6 + 1]@7
done;
[y:@12 := filter(x:10 + 1)]@11;
[sink(y:13)]@14
1 results.
F [15,2,10,16]
^C

**Comment by Hyunha** [comment]
Fix on 264c19233992fab98b7fd339f8b97cb795b5f5c5.

**Comment by Hyunha** [comment]
while 구문과 상관없이 mutation 알고리즘 자체에 버그가 있었음. 
그런데 예전에 실험한 건 어떻게 했던건지...?

**Comment by gugusny5758** [comment]
무한루프로 프로그램이 종료되지 않았을 뿐 mutation 결과는 AST형태로 찍혀 정상 적용 되는 걸로 생각하고 있었습니다..
올린 issue는 mutation은 주석처리로 돌리지 않은 상황에서의 무한루프가 있을 경우 분석기가 종료 되지 않는 경우인데 테스트 해보고 더 문제 있으면 이슈 올리겠습니다. 감사합니다.
